default:
 WORKING_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/proj-hetres/data"
 SIM_DIR: "02_intermediate/lidar_point_cloud/downsampled/fhi_outputs/"
 RF_DIR: "02_intermediate/rf/subsampled/"
 DESCRIPTORS: "all" # all, NDVI_diff, VHI, Structural params, Stats&PCA, custom
 CUTOFF: [0.33,0.33,0.33] # [0.2, 0.2, 0.2, 0.2, 0.2] # [0.35,0.29,0.33] 
