default:
 WORKING_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/proj-hetres/data"
 SIM_DIR: "02_intermediate/lidar_point_cloud/original/fhi_outputs/"
 TRAIN_DATA : false
 PATH_GT: "02_intermediate/ground_truth/GT_3p0_poly.shp"
 SIM_STATS_DIR: "02_intermediate/true_orthophoto/swisstopo/tables/nohf/"
 NDVI_DIR: "02_intermediate/satellite_images/ndvi_diff/"
 RF_DIR: "02_intermediate/rf/swisstopo/"
 