default:
 WORKING_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/proj-hetres/data/"
 DIR_LAS: "02_intermediate/lidar_point_cloud/original/dft_outputs/"
 DIR_EXTENT: "02_intermediate/AOI/tiles/"
 NEED_EXTENT: TRUE
 RES_CELL: 2.5
 SIM_DIR: "02_intermediate/lidar_point_cloud/original/fhi_outputs/"