default:
 SIM_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/data/02_intermediate/lidar_point_cloud/original/fhi_outputs/"
 RF_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/data/02_intermediate/rf/original/"
 DESCRIPTORS: "all" # all, NDVI_diff, VHI, Structural params, Stats&PCA, custom
 CUTOFF: [0.33,0.33,0.33] # [0.2, 0.2, 0.2, 0.2, 0.2] # [0.35,0.29,0.33] 
 RF_PRED: "pred_stats_PCA_NDVI_hf.shp"

production:
 SIM_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/data/02_intermediate/lidar_point_cloud/original/fhi_outputs/"
 RF_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/data/02_intermediate/rf/original/"
 DESCRIPTORS: "all" # all, NDVI_diff, VHI, Structural params, Stats&PCA, custom
 CUTOFF: [0.33,0.33,0.33] # [0.2, 0.2, 0.2, 0.2, 0.2] # [0.35,0.29,0.33] 
 RF_PRED: "pred_stats_PCA_NDVI_hf.shp"
