default:
 SIM_DIR: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/proj-hetres/data/02_intermediate/rf/original/gt_ana/"
 DESCRIPTORS: "all" # all, NDVI_diff, VHI, Structural params, Stats&PCA, custom
 CUTOFF: [0.33,0.33,0.33] # [0.2, 0.2, 0.2, 0.2, 0.2] # [0.35,0.29,0.33] 
 RF_PRED: "pred_stats_PCA_NDVI_hf.shp"
 PATH_GT: "C:/Users/cmarmy/Documents/STDL/Beeches/delivery/proj-hetres/data/02_intermediate/ground_truth/GT_3p0_point.shp" #"C:/Users/cmarmy/Documents/STDL/Beeches/delivery/proj-hetres/data/02_intermediate/ground_truth/STDL_releve_point_ok.shp"