function funCHM(pc,pathout)


##  [xyz_s, idxn_cell] = subsample([pc.record.x, pc.record.y, pc.record.z], ...
##     'method', 'mean', ...
##     'resolution', 0.1, ...
##     'fig', true, ...
##     'verbose', false);


 %% Computing a raster Canopy Height Model (CHM)

  cellSize = 0.5;
  [models, refmat] = elevationModels([pc.record.x, pc.record.y, pc.record.z], ...
      pc.record.classification, ...
      'classTerrain', [2], ...
      'classSurface', [3,4,5], ...
      'cellSize', cellSize, ...
      'interpolation', 'idw', ...
      'searchRadius', inf, ...
      'weightFunction', @(d) d^-3, ...
      'smoothingFilter', fspecial('gaussian', [3, 3], 0.8), ...
      'outputModels', {'terrain', 'surface', 'height'}, ...
      'fig', false, ...
      'verbose', true);


  %% Exporting the elevation models to ARC\INFO ASCII grid file

  % export the Digital Height Model (DHM) to an ARC\INFO ASCII grid file
  ASCwrite(strcat(pathout,'_chm.asc'), ...
      models.height.values, ...
      refmat, ...
      'precision', 2, ...
      'noData', -99999, ...
      'verbose', true);

  return
