install.packages('config')
install.packages('sf')
install.packages('terra')
install.packages('raster')
install.packages('pracma')
install.packages('EnvStats')
install.packages('Hmisc')
install.packages('lidR')
install.packages('randomForest')
install.packages('splitTools')
install.packages('caret')
install.packages('varImp')
install.packages('corrplot')
install.packages('Metrics')
install.packages('DeltaMAN')
install.packages('lctools')

