calculate_ndvi.py:
  working_directory: /mnt/data-01/gsalamin/deperissement-hetre/
  inputs:
    ortho: initial/True_ortho/Tiles
    tile_delimitation: initial/AOI/AOI_tiles/AOI_GT.shp

stats_beeches_pixels.py:
  original_ortho: false
  working_directory: /mnt/data-01/gsalamin/deperissement-hetre/
  destination_directory: final/downsampling_1on17/
  inputs:
    ortho: processed/filtered_images/downsampling_1on17
    tile_delimitation: initial/AOI/AOI_tiles/AOI_GT.shp
    north_chm: processed/CHM/CHM_binary_beurnevesin.tif
    south_chm: processed/CHM/CHM_binary_miecourt.tif
    beech_file: processed/trees/ok_trees.gpkg
    beech_layer: ok_trees_20_40_m

stats_per_tree.py:
  use_filter: true
  working_directory: /mnt/data-01/gsalamin/deperissement-hetre/
  inputs:
    ortho: initial/True_ortho/Tiles
    north_chm: processed/CHM/CHM_binary_beurnevesin.tif
    south_chm: processed/CHM/CHM_binary_miecourt.tif
    tile_delimitation: initial/AOI/AOI_tiles/AOI_GT.shp
    beech_file: processed/trees/ok_trees.gpkg
    beech_layer: ok_trees_20_40_m

filter_images.py:
  filter_type: thresholds    # valid values: "gaussian", "downsampling", "sieve" and "thresholds"
  working_directory: /mnt/data-01/gsalamin/deperissement-hetre/
  destination_directory: processed/filtered_images/5_colors
  tile_delimitation: initial/AOI/AOI_tiles/AOI_GT.shp